### ISSUE TITLE
Errors while proxying via Traefik

### ISSUE THREAD

**Issue by jochen-froehlich-gkgab** [cpvalente/ontime#135] opened 2022-05-24 07:33 UTC
Hi,

we are proxying the application via Traefik to get a valid HTTPS Site / Certificate. While the app works fine being accessed directly via HTTP and Port 4001 it throws an error while being proxied via HTTPS:

ontime version 1.0.1 
 TypeError: r.filter is not a function 
    at https://sub.domain.tld/static/js/main.161494c5.js:2:496043
    at O (https://sub.domain.tld/static/js/main.161494c5.js:2:356267)
    at Suspense
    at n (https://sub.domain.tld/static/js/main.161494c5.js:2:51719)
    at div
    at M (https://sub.domain.tld/static/js/main.161494c5.js:2:499894)
    at A (https://sub.domain.tld/static/js/main.161494c5.js:2:355526)
    at f (https://sub.domain.tld/static/js/main.161494c5.js:2:348344)
    at c (https://sub.domain.tld/static/js/main.161494c5.js:2:8408)
    at d (https://sub.domain.tld/static/js/main.161494c5.js:2:334416)
    at ze (https://sub.domain.tld/static/js/main.161494c5.js:2:50893)
    at https://sub.domain.tld/static/js/main.161494c5.js:2:571668
    at f (https://sub.domain.tld/static/js/main.161494c5.js:2:66308)
    at m (https://sub.domain.tld/static/js/main.161494c5.js:2:55394)
    at d (https://sub.domain.tld/static/js/main.161494c5.js:2:131464)
    at O (https://sub.domain.tld/static/js/main.161494c5.js:2:107197)
    at U (https://sub.domain.tld/static/js/main.161494c5.js:2:507039)
    at Wo (https://sub.domain.tld/static/js/main.161494c5.js:2:572274)

Any hints on how to fix this issue?
Thanks a lot.

**Comment by cpvalente** [comment] 2022-05-24 07:54
Hi @jochen-froehlich-gkgab 
Are you able to provide details on what is happenning in the browsers network tab and a small description of your setup?

**Comment by jochen-froehlich-gkgab** [comment] 2022-05-24 08:30
I see one request pending:

Name: ?EIO=4&transport=websocket
Type: websocket
Initiator: websocket.js:54
Request-URL: wss://0.0.15.161/socket.io/?EIO=4&transport=websocket

Description of Setup:
- Windows 10 running in a VM, hosting only the GetOnTime app. (can't wait for the headless version, preferable docker container ;-) )
- Traefik 2.6.6 running in Docker container on Ubuntu 20.04 LTS

Config an Traefik:
  routers:
    getontime-fe:
      rule: "Host(`sub.domain.tld`)"
      entryPoints: "websecure"
      tls:
        certresolver: cloudflare
      service: getontime-fe
  services:
    getontime-fe:
      loadBalancer:
        servers:
          - url: "http://172.27.220.27:4001"

Hope this helps.

**Comment by cpvalente** [comment] 2022-05-24 14:52
I dont have any immediate thoughts other than it could be some cors issue.
I am working on the docker container which might be a solution for this or at least help with the investigation.

I will keep the issue open meanwhile

**Comment by cpvalente** [comment] 2022-05-26 20:20
Hi @jochen-froehlich-gkgab, I managed to recreate and fix the issue.
I am working on a docker image, the fix will be released as part of the docker image release

Unfortunately I do not have an experimental branch setup...
If meanwhile you need a build to keep your work please feel free to reach out. Contact email is on the website

**Comment by cpvalente** [comment] 2022-05-29 09:22
Closing this issue since the problem is resolved. Fix is rolling out with the next release
@jochen-froehlich-gkgab it would be great to get some input on the docker container, feel free to reach out

**Closed by cpvalente** 2022-05-29 09:22 UTC
Labels: bug, help wanted

**Comment by jochen-froehlich-gkgab** [comment] 2022-05-30 06:25
The docker container works great. We are currently using only the different web URLs and not the OSC. Running everything inside docker makes our IT-footprint much smaller. Publishing via Traefik works awesome now.
Maybe you should note the default password for the editor somewhere or make it configurable via environment variables inside the docker-compose file.

**Comment by cpvalente** [comment] 2022-05-31 18:22
Hey @jochen-froehlich-gkgab 

That is really good news. I also made a smaller image using node-alpine which reduces the image size to 50MB ish.
It seems to be fully feature compatible and every so slightly more performant so I will probably move forwards with that.

Once this image is published it would be important to make a separate feature to add configuration of headless environments. Right now the best way to do it is by manually editing the db.json file
Perhaps you could assist me in creating a wishlist for what should be editable from environment variables?
