### ISSUE TITLE
Cuesheet Bug: Selected event is not fully shown

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#333] opened 2023-04-09 19:06 UTC
Hi!
Maybe it´s only on my machine... But the actual event (green) in the cuesheet is not fully shown.
Happens in Firefox, Edge (the fields there are much higher - strange?)
![grafik](https://user-images.githubusercontent.com/15065206/230791602-921801fd-dabd-4cd8-826d-6870dfd81158.png)

In Chrome it get´s even worse...
![grafik](https://user-images.githubusercontent.com/15065206/230791720-21571184-194b-4e27-82a2-1debb5feee15.png)

**Comment by cpvalente** [comment] 2023-04-09 19:12
Hey! Thank you again,

From the screenshots it seems that the reason for the change is that you don't have the user fields enabled (see chrome screenshot). Those are free text fields and are higher than the others.

Other than that, the bug has been confirmed and will be part of the next release

**Comment by Keksstar** [comment] 2023-04-09 19:21
>From the screenshots, the change seems to be because you don't have the user fields enabled (see chrome screenshot). Those are free text fields and are higher than the others.

Good catch! That´s it on the field hight. Thanks for pointing out.

Will see what Beta 4 brings 👍

**Closed** 2023-05-23 10:19 UTC
Labels: bug
