### ISSUE TITLE
Mode to apply automatic delay

### ISSUE THREAD

**Issue by 12xx12** [cpvalente/ontime#408] opened 2023-05-21 18:44 UTC
I really like this application. I'm just searching for a feature: 

I want a way to confirm that the next action should be started. I am thinking about a situation where you have speeches on stage and you have times set for the duration. The speaker takes more time than planned.

Now I can either use roll mode. This will take me to the next item. No delay applied. The next timer runs down.
Or I can use non-roll mode and the timer looses the time overtime.

I would either like the next button to confirm to go to the next item during roll mode and apply the delay or in non-roll mode to use the overtime and also apply this as a delay.

Is there a way to do this?

**Comment by cpvalente** [comment] 2023-05-21 19:23
Hi @12xx12 thank you for getting involved!

Short answer: there is currently no way of doing it

Slightly longer answer:

If I understand your request correctly, this is something that we would like to do, but have been unable to nail down the exact behaviour of.
Perhaps you have some thoughts that you can share there? https://github.com/cpvalente/ontime/issues/100#issuecomment-1556267435

**Comment by cpvalente** [comment] 2023-07-23 13:22
Closed as a duplicate of #100

**Closed by cpvalente** 2023-07-23 13:22 UTC
