### ISSUE TITLE
Toggle Message not working via Companion

### ISSUE THREAD

**Issue by desertdognl** [cpvalente/ontime#1015] opened 2024-05-29 08:57 UTC
The Toggle Message option in companion is not working with the 3.0.4 version of Ontime. Show and Hide works, just not toggle

**Comment by cpvalente** [comment] 2024-05-29 09:00
Thank you @desertdognl 
Would you mind moving this ticket to the companion module repo?

https://github.com/bitfocus/companion-module-getontime-ontime/issues
Can you also add information on which module version are you using?

**Comment by lukestein** [comment] 2024-05-29 15:29
This may be a duplicate of bitfocus/companion-module-getontime-ontime#58

**Comment by cpvalente** [comment] 2024-05-29 19:38
Thank you @lukestein, in that case it seems that it is just pending release from companion side

**Comment by lukestein** [comment] 2024-05-29 20:24
> Thank you @lukestein, in that case it seems that it is just pending release from companion side

Yup. I'd expect it to show up at the next Companion release (could be days, could be months)

**Closed** 2024-06-01 20:21 UTC
