### ISSUE TITLE
Ability to disable or change ALT+1 shortcut.

### ISSUE THREAD

**Issue by bilalg86** [cpvalente/ontime#1235] opened 2024-10-02 21:52 UTC
It would be helpful to be able to change or disable the Show App shortcut key combination ALT+1. For me it clashes with another software I use.

**Comment by cpvalente** [comment] 2024-10-03 05:28
Hi!
This shortcut will be removed from Ontime, this should be available in the next release

**Comment by cpvalente** [comment] 2024-10-05 07:17
Hi @bilalg86, can you please check the new release v3.6.0 and confirm whether the issue is resolved?

**Comment by cpvalente** [comment] 2024-10-09 20:08
closing this as completed and released

**Closed by cpvalente** 2024-10-09 20:08 UTC

**Comment by bilalg86** [comment] 2024-10-09 21:41
Thank you for the quick turn around and apologies for the late reply. I can confirm the issue is resolved.
