### ISSUE TITLE
Date support. 

### ISSUE THREAD

**Issue by bentodman** [cpvalente/ontime#1117] opened 2024-07-02 21:50 UTC
Hi I've been using this all weekend at Glasto and it's great but a thing thats stumpped me was having a show that runs over multiple days and running atomatically on clock. Would it be possible / Is it possible to add actual dates to the events so that it doesn't just pick the first event in the rundown with the correct time?

**Comment by cpvalente** [comment] 2024-07-03 06:45
Hi @bentodman, thank you for reaching out.

Good stuff with Glasto, it sounded like a lot of fun this year.

I have generally been against the idea of supporting a whole day and timestamp. 
Ontime is modelled closer against cue-to-cue software than schedule software and we gain in simplicity and power from this fact. 


In Ontime's case specifically, the event times are only used in Roll Mode. The expected behaviour here is that Roll Mode will always look for the next event after where it is. 
- Is there a reason for not having 2 project files (one for each day) and loading them in the morning?
- Did Roll mode not work for your use case? which 

However I realise that for planning of a stage as you likely had in Glastonbury, this is inconvenient and I agree that we could try to improve the usability.

While I believe that this is something we can and should improve, I am unsure whether full time stamped times is the solution
- Adding the date is just a small step into multi-day planning, we would need to change the interface and some of the infrastructure to accomodate for multiple days
- In event industry, the concept of day is not fixed. Back in my glasto days, a day would be from 10:00 - 03:00

Having said all of this, I would appreciate having some help thinking through how Ontime could be better for stage operations. If you have some availability to answer some questions please do get in touch at mail@getontiome.no

**Comment by bentodman** [comment] 2024-07-03 15:42
Hi I did use roll mode and it did work well until i had to restart for any reason.
I tried having several projects but there was no good place to split them as there was a continuous leapfrog of events happening. 
As for the day concept thing. I got around this by using blocks named for the 'days' i don't think you would need to show the date anywhere only use it as a trigger for roll mode.

I'll pop you an email!

**Comment by cpvalente** [comment] 2024-07-03 17:49
> Hi I did use roll mode and it did work well until i had to restart for any reason.
> 
> I tried having several projects but there was no good place to split them as there was a continuous leapfrog of events happening. 
> 
> As for the day concept thing. I got around this by using blocks named for the 'days' i don't think you would need to show the date anywhere only use it as a trigger for roll mode.
> 
> 
> 
> I'll pop you an email!

Thank you!

I just noticed that there was a typo on the email. Look forward to hearing from you
mail@getontime.no

**Comment by cpvalente** [comment] 2024-11-19 10:06
Closing this as we dont have an actionable path forwards
Feel free to reopen if we should discuss further, you can also reach on email (above) or on the new discord server ([link in the readme](https://github.com/cpvalente/ontime?tab=readme-ov-file#links))

**Closed** 2024-11-19 10:06 UTC

**Comment by DaveFH** [comment] 2025-07-21 21:06
Hello,

we tried OnTime as a Docker image last weekend as an alternative to Stagetimer.io at a smaller festival (about 3500 people per day and 2 stages).
Since this festival takes place on a meadow where internet access via mobile phone is not reliably guaranteed, we were looking for an OnPremise variant.
We came across OnTime.

We used a separate Docker container for each stage, so everything was easy to manage.

The only thing that was a bit annoying was that it was not possible to specify events over a period of 24 hours. It would be desirable if, as already described in this issue, it were possible to create an event for a period of more than 24 hours. To achieve this, we had individual projects for each day that had to be loaded in the morning. Unfortunately, this went wrong more than once during the stress of the festival.

It would be desirable if this could be realised somehow.

Many thanks for this great software and for making it available.

Regards
D
