### ISSUE TITLE
Cuesheet sync issue when adding event

### ISSUE THREAD

**Issue by silentpiranha** [cpvalente/ontime#258] opened 2022-11-19 20:20 UTC
When you add an event in the editor the columns in the Cuesheet refresh and show the new event.
But user columns do not refresh automatically. When this happens user columns are in row with the wrong event.
This resolves on page reload.

Expected behaviour: All columns should refresh to not get other contributors on the cuesheet confused.

**Comment by cpvalente** [comment] 2022-11-20 08:49
This sounds like a bug caused by performance optimisations. Let me have a look

**Comment by cpvalente** [comment] 2023-05-31 17:59
Closing the issue as we cannot recreate it

**Closed by cpvalente** 2023-05-31 17:59 UTC
